export const enum WorkerMessageType {
  START_GRAPH = `START_GRAPH`,
  UPDATE_NODES = `UPDATE_NODES`,
  UPDATE_LINKS = `UPDATE_LINKS`,

  INIT_GRAPH_COMPUTATION_WORKER = `INIT_GRAPH_COMPUTATION_WORKER`,
  UPDATE_VISIBLE_NODES = `UPDATE_VISIBLE_NODES`,
}

export const enum GraphEvents {
  FORCE_LAYOUT_COMPLETE = `FORCE_LAYOUT_COMPLETE`,
}

export enum GraphGraphics {
  CIRCLE_SIZE = 50,
  CIRCLE_SCALE_FACTOR = 1.5,
}

export enum GraphScales {
  CAN_SEE_BIG_NODES_WELL = 0.04608368838069515,
  CANNOT_SEE_ANYTHING_WELL = 0.05449999848460085,
}
